### ISSUE TITLE
Fix the Y2K bug

### ISSUE THREAD

**Issue by punktniklas** [punktniklas/NiKom#1]
Dates that includes years are displayd as "1xx" instead of "20xx". (E.g. "115" instead of "2015")

**Comment by punktniklas** [comment]
The simplest fix would be to keep the format with two digits for the year since there are many places that are formatted for having a date string with six characters (like "921224"). Todays date would be "150803". Any strong opinions about this?

Fabbes BBS has a patch which is not included in this source code where dates are written as "2015-08-03". This does create some formatting problems here and there. Look e.g. at "Lista Brev".

**Comment by fabiannorlin** [comment]
ISO 8601 demands four digits for the year, and this is maybe more easy to read, but I don't see any real problem with two digit years. At least not before year 2095. :)

**Comment by punktniklas** [comment]
Then let's do that as the fix for now. At least it's going to be correct.

If someone wants to improve how dates are displayed it can be done later.

I'm not very afraid of 2095.. 2038 is when the shit really is going to hit the fan. :-)

**Comment by punktniklas** [comment]
It turned out to be a little bit of both. In some places where formatting width was not important it will print the year with four digits.
