### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by punktniklas** [punktniklas/NiKom#11]
Introduce the use of locale.library and start translating bits and pieces to English. (Don't worry, the Swedish is not going away. :-) )

**Comment by joacimmelin** [comment]
There has been some questions about this on Fidonet where people want NiKom in english!

**Comment by punktniklas** [comment]
Most of the hard coded strings in the code are now localized. Left to do is:

- The commands for using the file areas
- The man pages
- The commands inside the editors
- Automatically generated notification messages. (Such as logins and logouts.)

**Comment by punktniklas** [comment]
Since partial localization is in place I'm closing this issue. New issues can be opened to complete more specific things.
