### ISSUE TITLE
More output from nikomfido

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#114]
It would be nice to, say, be able to add "-v" as a flag to nikomfido to get more output on what it's doing: 

"nikomfido updatefido -v" or something.

**Comment by punktniklas** [comment]
There are quite a lot of things that are logged to Fido.log. Is there anything missing there?

**Comment by punktniklas** [comment]
Can this issue be closed?

**Comment by joacimmelin** [comment]
Yep!
