### ISSUE TITLE
"skip subject" support for FTN forums as well

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#129]
Let's say a subject in a meeting (local or FTN) really doesn't interest you but you want to stay in that meeting anyway for other topics. 

A command as such would be very helpful: "skip subject" or "hoppa ärende".   Like this: 

"hoppa ärende BMW"

this would skip all posts with the subject "BMW" and mark them as read.

**Comment by punktniklas** [comment]
Isn't this exactly what the current "Skip" ("Hoppa Ärende") command already does?

**Comment by joacimmelin** [comment]
Skip subject does not work in Fido-meetings.

**Comment by punktniklas** [comment]
Changed the title of the issue
