### ISSUE TITLE
Go command bypass (Security flaw)

### ISSUE THREAD

**Issue by stripecat** [punktniklas/NiKom#132]
If users try to use the go/gå command to go to a meeting that they're not a member of, the command will offer them becoming a member of said meeting. This function does not check if they have status high enough to use the regular member command first.

This way, if you set the status of the member command to a status higher than the user has, the user can bypass this restriction by typing "go <meeting>" and then accepting to join instead.

Either remove the "do you want to join"-function, or make it validate statusr equirements of the member command before offering to let the user join.

**Comment by punktniklas** [comment]
As discussed earlier on NiKom BBS, I will remove the feature to ask if the user wants to become member.
