### ISSUE TITLE
MSGID kludges from Synchronet are not interpreted correctly

### ISSUE THREAD

**Issue by punktniklas** [punktniklas/NiKom#137]
The BBS software/FidoNet reader SynchroNet generates messages that has a MSGID kludge line on the format `"(something)@(FidoNet address) (timestamp)"` (e.g. `"29.fidonet-fn_sysop@1:2320/33 25a3ef3b"`)

Most other systems (including NiKom) use the format `"(FidoNet address) (timestamp)"` (e.g. `"1:2320/33 25a3ef3b"`) and this is the format that NiKom expects when parsing the MSGID kludge to try to figure out to and from address of a text. As a result the interpreted address may be wrong (especially the zone part). In the example above NiKom interprets it as "29:2320/33".

The FTS (http://ftsc.org/docs/fts-0009.001) is not super clear about what the format actually should be. I believe though that Synchronet's format is wrong. Other BBS softwares seems to have had similar problems: http://wiki.mysticbbs.com/doku.php?id=whats_new_112

Since it's unlikely that Synchronet will change, NiKom needs to understand this format.

**Comment by rswindell** [comment]
The FTN message ID isn't for "parsing". It's for unique message identification (e.g. for dupe detection) and reply-linking.  If you're parsing the message ID for some purpose (e.g. to figure out to and from address of a text), you're misusing this (optional) control information.
