### ISSUE TITLE
Go through ARexx scripts in distribution

### ISSUE THREAD

**Issue by punktniklas** [punktniklas/NiKom#18]
The ARexx scripts in DistrSkeleton/rexx were taken from the distribution of NiKom 1.60 as it was assumed that this would be the latest "clean" versions of the scripts suited for a new BBS setup.

It seems though as if NiKom 1.60 was shipped with whatever Kärkis BBS was running which can be either customized scripts or older versions since Kärkis BBS started with a pretty early version of NiKom.

Go through the scripts and compare with both earlier distributions and/or NiKom BBS.

**Comment by punktniklas** [comment]
@joacimmelin and @jayminer81 you may want to update the files in NiKom:Rexx since you both recently have set up your systems...

**Comment by joacimmelin** [comment]
Will do!  Thanks for heads-up!
