### ISSUE TITLE
Some users can't log in after v1.61 upgrade due to node type problem

### ISSUE THREAD

**Issue by jhofmann** [punktniklas/NiKom#19]
I do realize that https://github.com/punktniklas/NiKom/issues/10 probably already fixed this issue, but it's still an unreported problem and a patch, new release or workaround would be appreciated.

At least two users report not being able to log in after the upgrade. They get the message "Något allvarligt fel. prova med KOM-noden istället", this also happened with a test user I created if you select the menu node.

One of the users reported that he believe that he was not using the menu node (the other user loged out of our IRC channel before I had time to ask). This could be a separate problem with user settings being corrupted.

**Comment by punktniklas** [comment]
This error message is coming from the menu node. Which means that these users must actually be using the menu node. Unfortunately the ARexx UserInfo() function doesn't have an option for telling which nodetype a user has, if you wanted to make sure. You could always look at the user's Data file. The structure is defined in Include/NiKomStr.h and the field to look for is "shell".

Changes between 1.60 and 1.61 must have caused the menu node to stop working. Unfortunately this exact error message is printed out in a number of error cases so it's impossible right now to say what is going wrong.

I guess the workaround would be to remove the menu node from NodeTypes.cfg. The users that have that node type selected should then get a question when logging in what node type they want to use. (Where they only can choose one thing, the KOM node. Maybe it should be a bit smarter so you don't have to choose if there is only one choice.. :-) ).

For fixing the menu node I guess I can look into it a bit and if it's an easy fix we can make a fixed version of 1.61.
But going forward (for NiKom 2.0) I really have no interest in maintaining the menu node (as you can tell from #10 :-) ) If it's important to keep it alive someone has to step up and take care of it.

**Comment by coopdot** [comment]
I'm the user who reported the upgrade caused a node switch.
When trying to log in as my own user after the upgrade, the BBS is telling me I'm using menu node. When trying to log in as the guest user "gäst", the BBS tells me it's using the KOM node and gives me the user interface I'm used to.
So unless the nodes look the same after logging in and the menu node lets you type commands like "li är" and "åt ko", I never even seen a working menu node and my user accounts default node has been switched as a result of the steps taken when upgrading.

**Comment by punktniklas** [comment]
That's really weird if your user all of a sudden is set to using the menu mode.. I'm afraid I have no explanation to how that could have happened. The solution is the same though, the menu node needs to be removed from the available node types.

**Comment by joacimmelin** [comment]
I upgraded to 1.61 and I had previously (before the upgrade) removed the menu mode from nodetypes.cfg. I only have the KOM option left and have that as an option when I login after upgrading to 1.61 but even if I select the KOM option it does not work:

"Du har ingen förinställd nodtyp. 

Välj mellan: 

1: Den vanliga gamla KOM-noden. 

Val: 1
Finns ingen sådan nodtyp."

**Comment by punktniklas** [comment]
I'm closing this issue now. Feel free to reopen if there is anything that is not resolved.
