### ISSUE TITLE
v1.61 - Byt Tecken always selects SIS-7 with xterm

### ISSUE THREAD

**Issue by jhofmann** [punktniklas/NiKom#20]
When creating a new user or running "Byt Tecken" you get a list of four choices, on my setup number four (SIS-7) is automatically selected by the test printout for either "IBM CodePage 437 (PC8)" or "Macintosh".

My terminal is xterm (320) and my LC_CTYPE is sv_SE.ISO8859-1.

**Comment by punktniklas** [comment]
Can you elaborate a bit? What do you mean by "automatically selected"? Is this something that is new for 1.61? Is it just this command that has a problem or do you have character problems in general?

In what system (and window manager) do you run xterm? What about other environment variables such as LANG and XTERM_LOCALE? I've been tinkering a bit in Ubuntu that uses Gnome/Unity (or whatever it is these days) and I can't really get it to use ISO-8859-1 end to end..

**Comment by punktniklas** [comment]
ping? Is there still a problem or can this be closed?

**Comment by jhofmann** [comment]
Sorry, I forgot to respond.

With "automatically selected" I mean that after the printout of the menu there is no apperant pause, instead the system continues as if the number "4" was given as input.

I don't know if this is new to 1.61 or is caused by changes in my environment, I probably used AmTelnet when I first created my account. I don't have any other charset problems (unless I have run Byt Tecken with that user, after that I get åäö ÅÄÖ replaced with }{| ][\ and can't chage back).

My system is FreeBSD 10.2-RELEASE-p7, the window manager is awesome-3.5.6,1.

    $ echo $LANG

    $ echo $XTERM_LOCALE
    C

    $ locale
    LANG=
    LC_CTYPE=sv_SE.ISO8859-1
    LC_COLLATE="C"
    LC_TIME="C"
    LC_NUMERIC="C"
    LC_MONETARY="C"
    LC_MESSAGES="C"
    LC_ALL=

    $ echo räksmörgås | file -
    /dev/stdin: ISO-8859 text

**Comment by punktniklas** [comment]
This sounds really weird. :-)

First of all: There is a workaround in that you can give an argument to "byt tecken" so that it chooses a character set directly and never displays the menu and examples. "byt tecken 1" would choose ISO-8859-1.

How do the examples look for  the different character sets? Does it look correct for ISO-8859-1? What about the others? Can you paste in a "screen shot"?

When it does the automatic selection, does it print out the name of the selected character set after the prompt the same way it does when you choose yourself?

Is it only in this specific environment with this specific xterm that this happens? Have you tried any other terminals?

**Comment by jhofmann** [comment]
It's actually not that weird. ANSI has support for things like asking the terminal for its capabilities, terminal width and things like that. `xterm` even has support for mouse input (and other even crazier things). If you output random binary data you are likely to get some crap entered as input. (You can try this by something like `$ head /dev/random`.)

This is what I was referring to in my original report when I wrote:
> [...] is automatically selected **by the test printout** for either "IBM CodePage 437 (PC8)" or "Macintosh".

`byt tecken 1` is a nice workaround, but it's not the best for new users.

Here's the "screenshot":
>           ............... ......    ...... ................ ........
>           ::            : ::   :    ::   : ::             : ::      :
>           ::   .........: ::...:    ::   : ::   ..........: ::.......:
>           ::   :......... ......    ::   : ::   :  ........ ...........
>           ::            : ::   :    ::   : ::   :  ::     : ::         :
>           ::........    : ::   :    ::   : ::   :  ::..   : ::   ....   :
>           ........::    : ::   :....::   : ::   :....::   : ::   :  ::   :
>           ::            : ::             : ::             : ::   :   ::   :
>           ::............: ::.............: ::.............: ::...:    ::...:
>     
>            ... .:: . :.. .. ... ....   ..: ... . .:.   ::. .:. ::: ..: .::.
>                               ::: ..:.   .: :: .. ::. .:
>     
>                     Inget konto?                    Problem med svenska tecken?
>     Skriv 'NY' för att registrera en användare,   Se till att ditt terminalprogram
>     eller  'gäst'  med  lösenord 'gäst' för att   är  inställt  på  latin-1  eller
>     läsa mötena som besökare.                     ISO-8859-1.
>     
>     
>     Namn: ny
>     
>     Dessa teckenset finns. Ta det alternativ vars svenska tecken ser bra ut.
>     * markerar nuvarande val.
>     
>       Nr Namn                              Exempel
>     ----------------------------------------------
>       1: ISO 8859-1 (ISO Latin 1)          åäö ÅÄÖ
>       2: IBM CodePage (PC8)                
>                                             
>       3: Macintosh                          
>     
>       4: SIS-7 (SF7, m}svingar)            }{| ][\
>     
>     Om du bara ser ett alternativ ovan beror det av att ditt terminalprogram
>     strippar den 8:e biten i inkommande tecken. Om exemplet ser bra ut, ta
>     SIS-7 (dvs, tryck 4).
>     
>     Val: SIS-7
>     
>     
>     V{lkommen till den h{rliga och bortgl|mda BBS-v{rlden bortom Internet!
>     
>     H{r kan du prata med medlemmar i SUGA och annat folk f|r att f} hj{lp med din
>     Amiga, ta reda p} vad vi g|r eller diskutera vad helst du k{nner f|r. H{r finns
>     ocks} filareor d{r anv{ndare kan ladda upp och ner diverse sm}tt och gott.
>     
>     Som ny anv{ndare h{r kommer du inte vara validerad, vilket inneb{r att du
>     inte kan skriva eller kommentera i m|ten. Du blir validerad n{r en sysop
>     har kontrollerat att dina uppgifter ser riktiga ut. Vi vill att alla anger
>     minst sitt f|r och efternamn. Om du {r medlem i SUGA kan du ange det i
>     f{ltet "Annan Info" s} kommer du f} medlemsstatus s} fort vi bekr{ftat det.
>     Medlemmar har f|rm}ner som mer tid, tillg}ng till fler m|ten och fri
>     nerladdning av filer.
>     
>     Anv{nd kommandot "Info NyAnv" f|r l{sa den h{r texten igen. Om du aldrig anv{nt
>     en BBS tidigare och beh|ver ytterligare hj{lp, skriv "?" och tryck retur p}
>     kommandoprompten som visas efter att du fyllt i alla uppgifter.
>     
>     OBS! Om du inte anger ditt f|r och efternamn kommer du inte att f}
>          tilltr{de till basen.
>     
>     Nu {r det dags att fylla i uppgifter f|r din nya anv{ndare...
>     
>     
>     Namn: ;1;2;6;9;15;18;21;22c

I just tested this on Debian stable (8.2 / jessie) with `xterm 312-2`, it also has the same problem. `rxvt` on the other hand does work.

**Comment by punktniklas** [comment]
> byt tecken 1 is a nice workaround, but it's not the best for new users.

That's why I called it a workaround and not solution. :-)

I guess it makes sense that terminals can react on certain input. What is a bit weird though is that it so far I've only heard about your specific xterm having this problem. I've tried with xterm myself without being able to reproduce it. Also if this started with 1.61 it would be really weird. The printout of examples in different character sets have been there for a long time.

Anyway, it sounds like it's time to retire the examples and not print them out anymore. There was a time when many users would have absolutely no clue what character set to choose unless there was examples. But now things are probably different. Maybe this choice should not even be there for new users since almost everyone should want to use ISO-8859-1 these days.

**Comment by jhofmann** [comment]
But did you try xterm with latin-1? Here is a proven way to reproduce the problem (using Ubuntu, as I understand that you are using):

1. Download the ISO from here: http://ftp.availo.se/ubuntu-releases/15.10/ubuntu-15.10-desktop-amd64.iso
2. Load it up in VirtualBox (you will need internet access, I used 2 GB RAM)
3. Select "English" and "Try Ubuntu"
4. Click on the swirly icon top left, type "xterm" and start it
5. Type `sudo locale-gen sv_SE`
6. Type `LC_CTYPE=sv_SE xterm`
7. Optional: Click on "En" top right to select Swedish keyboard layout
   * Text Entry Settings...
   * "+", select Swedish from list
   * Close
   * Click "En" again, select Sv
8. In the new terminal, type `telnet suga.se 42512`
9. Type `ny`, observe problem. :)
