### ISSUE TITLE
UpdateFido

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#26]
Where is UpdateFido?  It's mentioned in the documentation for Fidonet import/export to NiKom but I can't see the binary anywhere. :)

**Comment by punktniklas** [comment]
It's in the NiKom 1.60 archive. (Together with a bunch of other small tools.)

The source code has not been imported into GitHub though. That should be done.

**Comment by joacimmelin** [comment]
Found it! Any parameters required when running it?

**Comment by punktniklas** [comment]
No, UpdateFido doesn't take any parameters.

Re-opening this issue to track importing of the source code of fido-related tools into GitHub.
