### ISSUE TITLE
Problems building NiKom

### ISSUE THREAD

**Issue by jayminer81** [punktniklas/NiKom#27]
I tried building NiKom with SAS/C 6.55 but the makefiles make assumptions that aren't true for most Amiga-systems. One being that they run Arexx-programs within the shell in a way a normal Amiga Shell can't do, and it also handles commands in backticks differently.

Some examples being convpragma.rexx which is called by just using convpragma as a command, another being the backticks used for NIKRELEASE, NIKVERSION and NIKREVISION (GetNiKomVersion.rexx) where AmigaShell will only expand one/the first backtick of a command line.

**Comment by punktniklas** [comment]
Commited 22a448f68a0241ba32e4c1a069dde7899367d38c with some changes. (Forgot to mention issue in commit message..)

**Comment by punktniklas** [comment]
Argh, forgot to mention in commit message again.. e2318843a81f26e0d41355ea377144237c3ae8af

**Comment by punktniklas** [comment]
Are all problems fixed now so this issue can be closed?

**Comment by jayminer81** [comment]
Yes, everything is working fine now!

**Comment by punktniklas** [comment]
Great, closing the issue!
