### ISSUE TITLE
Full release build for 2.0

### ISSUE THREAD

**Issue by punktniklas** [punktniklas/NiKom#28]
Make it ready to create a full release archive for NiKom 2.0 when it's time to make the release. Some things that probably should be done:

- A script that compiles all of NiKom cleanly, including tools in the Tools directory and creates an archive from files in the DistrSkeleton directory. Preferably it should leverage the existing makebindistr script so there isn't a lot of duplication. (Perhaps it should also build both 68000 and 68020 version of the binaries.)
- Update documentation if necessary. Remove all references to specific version in the docs so it doesn't have to be changed all the time.
- Perhaps generate HTML from the AmigaGuide files and include both in the release?

Right now third party libraries and programs (fifo, xpr, move etc) are not checked in since git is not very good at handling binary files. So they can't easily be included by the script. Maybe a separate archive can be made for these that doesn't have to be updated for each release. Or maybe just make them easily available on nikom.org.

I'm sure more bullet points will come up. :-)

**Comment by joacimmelin** [comment]
Yes please for 68000 and 68020, at least until I get an accelerator card for my A2000.  :)

**Comment by punktniklas** [comment]
@jayminer81 

After discussions on NiKom BBS. There are three use cases that should be easy to perform.

1. Create an archive with cleanly compiled core binaries (library, server and nodes) for easy deployment to a test environment.
2. Create an archive with all binaries, both 68000 and 68020, for making a binary distribution. (For smaller/bug fix releases.)
3. Create an archive with all binaries and all other files needed to setup a NiKom system.

**Comment by punktniklas** [comment]
Replace all references to Kärkis BBS in texts (like login and logout texts) and config files with generic "new BBS" references.
