### ISSUE TITLE
New command: "fotnot"

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#35]
"fotnot" - add a comment to a text in form of a footnote.  Maybe to be used for clarification of something silly you just wrote.

**Comment by punktniklas** [comment]
Do you have an example how a text with a footnote looks in other KOM systems?

**Comment by joacimmelin** [comment]
Example from memory (I don't have a SKOM account anymore):

Text 763 Möte: NiKom erfarenhetsutbyte 20151217 13:03
Skriven av Joacim Melin #1
Ärende: Ny tosser

Som jag kanske nämnde lite snabbt häromkvällen har jag bytt tosser från
Traptoss till Crashmail. Den senare är dessutom skriven av svenska
utvecklare och i oregistrerat tillstånd klarar den två "upplänkar", i mitt
fall Fidonet och Agoranet. Den har dessutom ett grafiskt
användargränssnitt vilket är trevligt och som grädde på moset kunde den
också importera konfigurationen från Traptoss.

Finns på Aminet. Rekommenderas för de som vill leka Fidonet eller
liknande. Och ja, den fungerar med 68000-proppen. :)

(Slut på text 763 av Joacim Melin #1)

(Se) tiden --> Fotnot

Skriv in din fotnot nedan. Spara med CTRL-Z, eller kasta bort den med !bo. 
1: Ska väl säga också att Crashmail är snabbare än Traptoss. 

Fotnot sparad!

(Se) tiden --> läs 763

Text 763 Möte: NiKom erfarenhetsutbyte 20151217 13:03
Skriven av Joacim Melin #1
Ärende: Ny tosser

Som jag kanske nämnde lite snabbt häromkvällen har jag bytt tosser från
Traptoss till Crashmail. Den senare är dessutom skriven av svenska
utvecklare och i oregistrerat tillstånd klarar den två "upplänkar", i mitt
fall Fidonet och Agoranet. Den har dessutom ett grafiskt
användargränssnitt vilket är trevligt och som grädde på moset kunde den
också importera konfigurationen från Traptoss.

Finns på Aminet. Rekommenderas för de som vill leka Fidonet eller
liknande. Och ja, den fungerar med 68000-proppen. :)

(Slut på text 763 av Joacim Melin #1)

Fotnot: Ska väl säga också att Crashmail är snabbare än Traptoss.

(Se) tiden -->

**Comment by punktniklas** [comment]
Can the footnote be multiple lines? The way it's displayed after the text in your example suggests it can only be one line.

**Comment by joacimmelin** [comment]
It can certainly be several lines.
