### ISSUE TITLE
New command: "!flytta kommentar"

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#37]
"!flytta kommentar" - move comment to another meeting within the editor.

**Comment by punktniklas** [comment]
This has existed since the dawn of time.

In the normal editor: Ctrl-Q and then "flytta <forum>"
In the line editor: "!flytta <forum>"

I thought we already cleared this up. :-)

**Comment by joacimmelin** [comment]
Yes it exists but it's not logical.  Why not make it accessible w/o entering ctrl-q? 

How do I access the line editor and what's the difference from the line editor and the normal editor?

**Comment by punktniklas** [comment]
This sounds more like you don't know how the editors in NiKom work. Read "Editorer.doc" and ask on NiKom BBS if there are more questions on how they work.
