### ISSUE TITLE
bulletin.txt

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#39]
Is it possible to force bulletin.txt to be shown every time?

**Comment by punktniklas** [comment]
No, the whole idea with the bulletin is to only show it when it has been updated. I you want to display a text every time at login you can do it in the post login ARexx script.

**Comment by joacimmelin** [comment]
Example from memory (I don't have a SKOM account anymore): 

Text 763  Möte: NiKom erfarenhetsutbyte    20151217 13:03
Skriven av Joacim Melin #1
Ärende: Ny tosser

Som jag kanske nämnde lite snabbt häromkvällen har jag bytt tosser från
Traptoss till Crashmail. Den senare är dessutom skriven av svenska
utvecklare och i oregistrerat tillstånd klarar den två "upplänkar", i mitt
fall Fidonet och Agoranet.  Den har dessutom ett grafiskt
användargränssnitt vilket är trevligt och som grädde på moset kunde den
också importera konfigurationen från Traptoss.

Finns på Aminet. Rekommenderas för de som vill leka Fidonet eller
liknande. Och ja, den fungerar med 68000-proppen.  :)

(Slut på text 763 av Joacim Melin #1)   

(Se) tiden -->  Fotnot

Skriv in din fotnot nedan. Spara med CTRL-Z, eller kasta bort den med !bo. 
1: Ska väl säga också att Crashmail är snabbare än Traptoss. 
<cltr-z>
Fotnot sparad!

(Se) tiden --> läs 763

Text 763  Möte: NiKom erfarenhetsutbyte    20151217 13:03
Skriven av Joacim Melin #1
Ärende: Ny tosser

Som jag kanske nämnde lite snabbt häromkvällen har jag bytt tosser från
Traptoss till Crashmail. Den senare är dessutom skriven av svenska
utvecklare och i oregistrerat tillstånd klarar den två "upplänkar", i mitt
fall Fidonet och Agoranet.  Den har dessutom ett grafiskt
användargränssnitt vilket är trevligt och som grädde på moset kunde den
också importera konfigurationen från Traptoss.

Finns på Aminet. Rekommenderas för de som vill leka Fidonet eller
liknande. Och ja, den fungerar med 68000-proppen.  :)

(Slut på text 763 av Joacim Melin #1)   
Fotnot: Ska väl säga också att Crashmail är snabbare än Traptoss. 

(Se) tiden -->

**Comment by jayminer81** [comment]
I think this is a great idea, there are times when I have missed something like this when I've written a message and would like to add something to it just afterwards.

But I'm guessing the biggest problem is, if someone read the message before a 'fotnot' was added, they will never get to see it?

**Comment by joacimmelin** [comment]
That is correct - they will not see the footnote until it has been added and if they read the message before  the footnote is added they will not see it unless they read the entire message again after the footnote has been added.

**Comment by punktniklas** [comment]
You wrote this into the wrong issue. :-)
