### ISSUE TITLE
Plugins and new third-party commands

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#40]
I've been checking out some third party commands and "plugins" from when NiKom was in heavy use. But I'm hesitant to try them in case something works or doesn't. 

Maybe a good idea to set up some sort of "certification" process where people can try third party stuff (and download them from nikom.org) and then mark them as working or non-working (maybe like the plugin directory at wordpress.org)

**Comment by punktniklas** [comment]
A certification process sounds kind of heavyweight for something that is as niche as running a BBS with NiKom. It may have made sense in the hay days but now I think it's more work than benefit.

If someone wants to do something like this they are of course welcome to do it (and I could host things on nikom.org if needed) but it's out of scope for the core NiKom project.
