### ISSUE TITLE
Fido-related bug when adding new meeting

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#44]
When adding a third fido style network, the prenode hangs hard (cannot even be terminated in the OS) when I try to create a new meeting for that network.  

A work-around is to create the new meeting with valid settings except which domain the meeting is part of. I simply choose another domain (i.e Fidonet) and then, when the meeting is created, change it to the correct domain.

**Comment by punktniklas** [comment]
Offline discussion has clarified the problem to that at least in NiKomCon it doesn't really hang. It just doesn't accept the correct input. GetNumber() was called with the wrong parameters. This is now fixed.

It seems to work in NiKomSer as well now. Why it was hanging hard is still unknown.
