### ISSUE TITLE
Issue: Can't delete echomail

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#46]
When posting a text in a fidonet conference, I can't delete my own text before it's been tossed and sent away to the hub. 

The error message is very confusing also.   Example: 

Text 945  Möte: General Discussion (Fsxnet)    16 Mar 16  18:24:51
Skriven av Joacim Melin (21:1/116.0)
Till: Paul Hayton
Ärende: Re: AMIBinkd

!bo

--- NiKom v2.0.0
 * Origin: Delta City (deltacity.se, +46-8-6058800) (21:1/116.0)

(Slut på text 945 av Joacim Melin)  

(Se) tiden --> rad te 945

Du kan bara radera texter av dig själv!

(Se) tiden -->

**Comment by punktniklas** [comment]
Deleting texts is not supported for FidoNet forums. There are several problems with being able to delete a Fido text.

- I'm not sure whether NiKom can tell whether a text has been tossed and sent out or not. If it has it shouldn't really be deleted.
- If the text is not the highest text there will be a gap, which is not supported.
- If the text is the highest and gets deleted then the next text (written or imported) will get the same number. If someone had already read the old deleted text they will never get to read the new text with the same number.
