### ISSUE TITLE
Mark text as unread

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#61]
One feature I'd like is this: 

Suppose I read message  42 in the meeting "Hot Dang NiKom rules!" and I want to mark it as unread for the next time I logon to the BBS, I would like to be able to enter a command like "oläs" and then carry on reading other messages in the same meeting or another meeting.  The next time I login to the BBS, message 42 will be there for me to read again.

**Comment by punktniklas** [comment]
I'm not sure marking a text as unread is really what you want.. If you mark text x as unread you will not be able to automatically read any texts with number higher than x (except for when you read them as part of a reply chain) in the same forum. The KOM engine will always guide you to the oldest texts first. To make some special exception to get it to skip the text in this session but not the next sounds like a pretty confusing user experience.

It rather sounds like you want some kind of bookmark feature? Please make a post on NiKom BBS so we can discuss what the feature really should be.

As a sidenote: There are functions in the ARexx interface to mark texts as read/unread.

**Comment by punktniklas** [comment]
I think the solution here is to revamp the existing "Mark Text" command to preserve the texts that are marked between logins and to make a command that takes the texts that are marked and makes them unread. (And probably flush them from the marked text list at the same time)

**Comment by punktniklas** [comment]
This would also eliminate issue #73
