### ISSUE TITLE
Mark already read texts as read when carrier drops

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#62]
Occationally I will loose my connection to a NiKom-based BBS and when I login again, I have to re-read all texts/posts again, including my own replies.   Surely there must be a way to have PreNode commit a read/write status to a user database when/if the "carrier" is dropped?

**Comment by punktniklas** [comment]
NiKomSer (not PreNode) does save the user data when it detects that the connection is lost. Just like when you logout. What likely happens in your case is that the NiKom side hasn't discovered that the connection is lost yet and when you log in again your old session is still active and hasn't been saved to disk yet.

**Comment by joacimmelin** [comment]
Then can NikomSer maybe issue a save user data command or whatever every X seconds or so?

**Comment by punktniklas** [comment]
Automatic saving of user data every minute has been implemented for v2.4.
