### ISSUE TITLE
A default Senaste.dat is missing

### ISSUE THREAD

**Issue by patrikaxelsson** [punktniklas/NiKom#65]
If you are installing a new system, there is no DatoCfg/Senaste.dat included which will prevent NikServer from starting.

Simply creating an empty DatoCfg/Senaste.dat is not enough to be able to start NikServer.

[NiKomInstall_Senaste.dat.txt](https://github.com/punktniklas/NiKom/files/485697/NiKomInstall_Senaste.dat.txt)

**Comment by punktniklas** [comment]
InitNiKom should have created one. That must have gotten lost when I refactored it. As a workaround you can create a file that 2304 bytes in size and contains all zero bytes.

**Comment by patrikaxelsson** [comment]
Ghansks for the workaround!
