### ISSUE TITLE
Logger warns about missing NiKom:Log directory

### ISSUE THREAD

**Issue by patrikaxelsson** [punktniklas/NiKom#67]
After doing a clean installation of NiKom, there will be lines like this in the shell where you started NikomCon or PreNode:
`LOG ERROR! Can't open log file NiKom:Log/Usage.log`

The Log directory is not mentioned in doc/Installation.doc or created by InitNiKom. Maybe the logger could create it by itself, like it does with the Usage.log file itself?

**Comment by punktniklas** [comment]
That was actually a deliberate decision not to automatically create the directory. Partly to avoid having to check for the directory every time something is logged.

Also, even though the log destination is not configurable right now I had in mind that it may be that later on. Then you could configure the log directory to be e.g. "Foo:" which can not be created.

It should be mentioned in the documentation though.
