### ISSUE TITLE
Deleting a post doesn't actually delete a post

### ISSUE THREAD

**Issue by joacimmelin** [punktniklas/NiKom#79]
Deleting a post with "radera text <number>" results in the text still being available. Note the message that says it's deleted when I enter the text number and then the text is shown anyway. 

(Se) tiden --> radera text 3113
(Se) tiden --> 3113

Text 3113 är raderad.

Text 3113  Möte: Länktips    20170216 13:44
Skriven av Joacim Melin #1
Ärende: Degoo

svensk molnbackup, 100GB gratis yta.

www.degoo.com

(Slut på text 3113 av Joacim Melin #1)

**Comment by punktniklas** [comment]
That's because you are sysop. For normal users it will just say that it's deleted.

**Comment by joacimmelin** [comment]
Not very logical, though.

**Comment by punktniklas** [comment]
Well, as the sysop you should have the possibility to know what is going on on your BBS. And that includes being able to read messages that have been deleted.
